"""
Final thesis sensitivity scatter plots and PPO-vs-nominal validation table.

New validation-data format
--------------------------
This script reads the validation CSV files generated by the PPO-vs-nominal
replay validation script:

    Final Plots/data/sensitivity_tli/tli_validation_samples.csv
    Final Plots/data/sensitivity_mcc/mcc_validation_samples.csv

It outputs:

    sensitivity_tli_success_scatter.png/.pdf
    sensitivity_mcc_success_scatter.png/.pdf
    sensitivity_ppo_vs_nominal_table.csv
    sensitivity_ppo_vs_nominal_table.tex
    sensitivity_ppo_vs_nominal_table.txt

The public main(data_dir, output_dir) signature is intentionally kept unchanged
so this file still works when called from plot_all.py as:

    from scripts.plot_sensitivity_analysis import main as run
    run(DATA_DIR, THESIS_DIR)

Scatter interpretation
----------------------
The scatter plots show the PPO rerun result for each perturbed initial condition.
The x-axis is the actual position perturbation norm in km and the y-axis is the
actual velocity perturbation norm in m/s.

Table interpretation
--------------------
The LaTeX table compares PPO adaptation against replaying the nominal action
sequence for each perturbation cell. Positive Delta means PPO has a higher
success rate than nominal replay.
"""

from __future__ import annotations

from pathlib import Path
import sys
import csv
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# PROJECT PATHS
# ============================================================

FINAL_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = FINAL_ROOT.parent

sys.path.insert(0, str(FINAL_ROOT))
sys.path.insert(0, str(PROJECT_ROOT))


# Keep compatibility with your thesis plotting style.
# If the style module is unavailable, the script still runs with basic matplotlib.
try:
    from style.thesis_style import (
        apply_thesis_style,
        get_figsize,
        clean_axis,
        save_thesis_figure,
        ieee_title,
    )
except Exception:
    def apply_thesis_style():
        plt.rcParams.update({
            "font.size": 10,
            "axes.grid": True,
            "figure.dpi": 160,
            "savefig.dpi": 300,
        })

    def get_figsize(kind="single"):
        return (3.5, 2.8) if kind == "single" else (7.0, 4.0)

    def clean_axis(ax, grid=True):
        ax.grid(grid, alpha=0.25)

    def save_thesis_figure(fig, path_base):
        path_base = Path(path_base)
        path_base.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(path_base.with_suffix(".png"), bbox_inches="tight")
        fig.savefig(path_base.with_suffix(".pdf"), bbox_inches="tight")

    def ieee_title(text):
        return text


# ============================================================
# SETTINGS
# ============================================================

FIGSIZE_KIND = "single"

POINT_SIZE = 14
POINT_ALPHA = 0.85

SUCCESS_COLOR = "gold"
FAILURE_COLOR = "#1f4e79"

SHOW_TITLE = True
SHOW_GRID = True

# Success definitions used for the new validation CSV format.
# The clean flag excludes trajectories that later impact Earth/Moon.
PPO_SUCCESS_COL = "rerun_ppo_clean_success_no_impact"
NOMINAL_SUCCESS_COL = "nominal_clean_success_no_impact"

# Required validation CSV columns.
REQUIRED_COLUMNS = [
    "sigma_pos_m",
    "sigma_vel_mps",
    "dx_m",
    "dy_m",
    "dvx_mps",
    "dvy_mps",
    PPO_SUCCESS_COL,
    NOMINAL_SUCCESS_COL,
]

# Expected validation folders under Final Plots/data.
MODE_INFO = {
    "tli": {
        "folder": "sensitivity_tli",
        "csv": "tli_validation_samples.csv",
        "label": "TLI",
    },
    "mcc": {
        "folder": "sensitivity_mcc",
        "csv": "mcc_validation_samples.csv",
        "label": "MCC",
    },
}


# ============================================================
# BASIC HELPERS
# ============================================================

def parse_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    if isinstance(x, (np.bool_,)):
        return bool(x)
    s = str(x).strip().lower()
    return s in ("true", "1", "yes", "y", "success")


def parse_float(row: Dict[str, str], key: str) -> float:
    try:
        return float(row[key])
    except Exception as exc:
        raise ValueError(f"Could not parse column '{key}' as float. Bad row: {row}") from exc


def format_float_for_table(x: float) -> str:
    if x is None or not np.isfinite(float(x)):
        return "--"
    x = float(x)
    if abs(x - round(x)) < 1e-9:
        return f"{int(round(x))}"
    return f"{x:.3g}"


def format_rate(x: float) -> str:
    if x is None or not np.isfinite(float(x)):
        return "--"
    return f"{100.0 * float(x):.1f}"


def format_delta(delta_fraction: float) -> str:
    if delta_fraction is None or not np.isfinite(float(delta_fraction)):
        return "--"
    value = 100.0 * float(delta_fraction)
    return f"{value:+.1f}"


def case_label(sigma_pos_m: float, sigma_vel_mps: float) -> str:
    pos_zero = np.isclose(float(sigma_pos_m), 0.0)
    vel_zero = np.isclose(float(sigma_vel_mps), 0.0)

    if pos_zero and vel_zero:
        return "Nominal"
    if (not pos_zero) and vel_zero:
        return "Position only"
    if pos_zero and (not vel_zero):
        return "Velocity only"
    return "Position+velocity"


def case_sort_key(row: Dict[str, Any]) -> Tuple[int, float, float]:
    sp = float(row["sigma_pos_m"])
    sv = float(row["sigma_vel_mps"])
    label = case_label(sp, sv)
    order = {
        "Nominal": 0,
        "Position only": 1,
        "Velocity only": 2,
        "Position+velocity": 3,
    }.get(label, 10)
    return order, sp, sv


def set_limits(ax, x, y):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    x = x[np.isfinite(x)]
    y = y[np.isfinite(y)]

    if len(x) == 0 or len(y) == 0:
        return

    xmax = np.nanmax(x)
    ymax = np.nanmax(y)
    xmin = np.nanmin(x)
    ymin = np.nanmin(y)

    xpad = max(0.05 * max(abs(xmax), 1.0), 0.25)
    ypad = max(0.08 * max(abs(ymax), 1.0), 1.0)

    ax.set_xlim(min(-xpad, xmin - 0.2 * xpad), xmax + xpad)
    ax.set_ylim(min(-ypad, ymin - 0.2 * ypad), ymax + ypad)


def add_success_legend(ax):
    fail_proxy = ax.scatter([], [], s=POINT_SIZE, color=FAILURE_COLOR, label="Failure")
    success_proxy = ax.scatter([], [], s=POINT_SIZE, color=SUCCESS_COLOR, label="Success")
    ax.legend(handles=[fail_proxy, success_proxy], loc="best", frameon=True)


# ============================================================
# CSV LOADING
# ============================================================

def find_validation_csv(data_dir: Path, mode: str) -> Optional[Path]:
    """Find the expected validation CSV for one mode."""
    data_dir = Path(data_dir)
    info = MODE_INFO[mode]

    preferred = data_dir / info["folder"] / info["csv"]
    if preferred.exists():
        return preferred

    # Helpful fallback if the user accidentally keeps the file one level deeper.
    candidates = sorted((data_dir / info["folder"]).rglob(info["csv"])) if (data_dir / info["folder"]).exists() else []
    if candidates:
        return candidates[0]

    # Last-resort fallback under the full data folder.
    candidates = sorted(data_dir.rglob(info["csv"]))
    if candidates:
        return candidates[0]

    return None


def read_validation_csv(path: Path, mode: str) -> Dict[str, np.ndarray]:
    rows: List[Dict[str, str]] = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames or []
        missing = [c for c in REQUIRED_COLUMNS if c not in fieldnames]
        if missing:
            raise ValueError(
                f"{path} is missing required columns: {missing}\n"
                f"Available columns are: {fieldnames}"
            )
        rows = list(reader)

    if not rows:
        raise ValueError(f"{path} contains no data rows.")

    sigma_pos = np.array([parse_float(r, "sigma_pos_m") for r in rows], dtype=float)
    sigma_vel = np.array([parse_float(r, "sigma_vel_mps") for r in rows], dtype=float)
    dx = np.array([parse_float(r, "dx_m") for r in rows], dtype=float)
    dy = np.array([parse_float(r, "dy_m") for r in rows], dtype=float)
    dvx = np.array([parse_float(r, "dvx_mps") for r in rows], dtype=float)
    dvy = np.array([parse_float(r, "dvy_mps") for r in rows], dtype=float)
    ppo_success = np.array([parse_bool(r[PPO_SUCCESS_COL]) for r in rows], dtype=bool)
    nominal_success = np.array([parse_bool(r[NOMINAL_SUCCESS_COL]) for r in rows], dtype=bool)

    x_km = np.sqrt(dx ** 2 + dy ** 2) / 1000.0
    y_mps = np.sqrt(dvx ** 2 + dvy ** 2)

    return {
        "mode": np.array([mode]),
        "path": np.array([str(path)]),
        "sigma_pos_m": sigma_pos,
        "sigma_vel_mps": sigma_vel,
        "dx_m": dx,
        "dy_m": dy,
        "dvx_mps": dvx,
        "dvy_mps": dvy,
        "x_km": x_km,
        "y_mps": y_mps,
        "ppo_success": ppo_success,
        "nominal_success": nominal_success,
    }


# ============================================================
# PLOTTING
# ============================================================

def plot_ppo_success_scatter(data: Dict[str, np.ndarray], output_dir: Path) -> Dict[str, Any]:
    apply_thesis_style()

    mode = str(data["mode"][0]).lower()
    mode_label = MODE_INFO[mode]["label"]
    x = np.asarray(data["x_km"], dtype=float)
    y = np.asarray(data["y_mps"], dtype=float)
    success = np.asarray(data["ppo_success"], dtype=bool)

    fig, ax = plt.subplots(figsize=get_figsize(FIGSIZE_KIND))

    fail = ~success

    ax.scatter(
        x[fail],
        y[fail],
        s=POINT_SIZE,
        color=FAILURE_COLOR,
        alpha=POINT_ALPHA,
        linewidths=0,
        zorder=5,
    )

    ax.scatter(
        x[success],
        y[success],
        s=POINT_SIZE,
        color=SUCCESS_COLOR,
        alpha=POINT_ALPHA,
        edgecolors="black",
        linewidths=0.15,
        zorder=10,
    )

    clean_axis(ax, grid=SHOW_GRID)
    ax.set_xlabel(r"Actual position perturbation norm [km]")
    ax.set_ylabel(r"Actual velocity perturbation norm [m/s]")

    if SHOW_TITLE:
        ax.set_title(ieee_title(f"PPO-{mode_label} sensitivity scatter"))

    set_limits(ax, x, y)
    add_success_legend(ax)

    success_rate = 100.0 * float(np.mean(success))
    ax.text(
        0.02,
        0.98,
        f"PPO success: {success_rate:.1f}%",
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=9,
        bbox=dict(facecolor="white", edgecolor="black", alpha=0.85),
    )

    out_name = f"sensitivity_{mode}_success_scatter"
    save_thesis_figure(fig, Path(output_dir) / out_name)
    plt.close(fig)

    print(f"[OK] Saved {out_name}.png/.pdf from {Path(str(data['path'][0])).name}")

    return {
        "mode": mode,
        "n": int(len(success)),
        "ppo_success_rate": float(np.mean(success)),
        "nominal_success_rate": float(np.mean(data["nominal_success"])),
    }


# ============================================================
# TABLE SUMMARY
# ============================================================

def summarize_by_cell(data: Dict[str, np.ndarray]) -> List[Dict[str, Any]]:
    sigma_pos = np.asarray(data["sigma_pos_m"], dtype=float)
    sigma_vel = np.asarray(data["sigma_vel_mps"], dtype=float)
    ppo = np.asarray(data["ppo_success"], dtype=bool)
    nominal = np.asarray(data["nominal_success"], dtype=bool)

    unique_cells = sorted(set(zip(sigma_pos.tolist(), sigma_vel.tolist())), key=lambda p: case_sort_key({"sigma_pos_m": p[0], "sigma_vel_mps": p[1]}))

    rows: List[Dict[str, Any]] = []
    for sp, sv in unique_cells:
        mask = np.isclose(sigma_pos, sp) & np.isclose(sigma_vel, sv)
        n = int(np.sum(mask))
        if n == 0:
            continue
        ppo_rate = float(np.mean(ppo[mask]))
        nominal_rate = float(np.mean(nominal[mask]))
        rows.append({
            "case": case_label(sp, sv),
            "sigma_pos_m": float(sp),
            "sigma_vel_mps": float(sv),
            "n": n,
            "ppo_success_rate": ppo_rate,
            "nominal_success_rate": nominal_rate,
            "delta_rate": ppo_rate - nominal_rate,
        })

    rows.append({
        "case": "Total",
        "sigma_pos_m": np.nan,
        "sigma_vel_mps": np.nan,
        "n": int(len(ppo)),
        "ppo_success_rate": float(np.mean(ppo)),
        "nominal_success_rate": float(np.mean(nominal)),
        "delta_rate": float(np.mean(ppo) - np.mean(nominal)),
    })

    return rows


def save_single_mode_table(rows, mode_name, output_dir):

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    tex_path = output_dir / f"sensitivity_{mode_name}_ppo_vs_nominal_table.tex"

    with open(tex_path, "w", encoding="utf-8") as f:

        f.write("\\begin{table}[t]\n")
        f.write("\\centering\n")
        f.write("\\small\n")
        f.write("\\begin{tabular}{lrrrrrr}\n")
        f.write("\\hline\n")
        f.write("Case & $\\sigma_r$ & $\\sigma_v$ & $N$ & PPO & Nom. & $\\Delta$ \\\\\n")
        f.write(" & [m] & [m/s] & & [\\%] & [\\%] & [pp] \\\\\n")
        f.write("\\hline\n")

        for r in rows:

            if r["case"] == "Total":
                sig_r = "--"
                sig_v = "--"
                f.write("\\hline\n")
            else:
                sig_r = f"{r['sigma_pos_m']:.0f}"
                sig_v = f"{r['sigma_vel_mps']:.0f}"

            f.write(
                f"{r['case']} & "
                f"{sig_r} & "
                f"{sig_v} & "
                f"{r['n']} & "
                f"{100*r['ppo_success_rate']:.1f} & "
                f"{100*r['nominal_success_rate']:.1f} & "
                f"{100*r['delta_rate']:+.1f} \\\\\n"
            )

        f.write("\\hline\n")
        f.write("\\end{tabular}\n")
        f.write(
            f"\\caption{{{mode_name.upper()} sensitivity validation comparing PPO adaptation against nominal-action replay.}}\n"
        )
        f.write(
            f"\\label{{tab:{mode_name}_sensitivity}}\n"
        )
        f.write("\\end{table}\n")

    return tex_path


# ============================================================
# MAIN ENTRY POINT USED BY plot_all.py
# ============================================================

def main(data_dir=None, output_dir=None):
    """
    Main entry point.

    Kept compatible with plot_all.py:
        run(DATA_DIR, THESIS_DIR)
    """
    if data_dir is None:
        data_dir = FINAL_ROOT / "data"

    if output_dir is None:
        output_dir = FINAL_ROOT / "outputs" / "thesis_ready"

    data_dir = Path(data_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "-" * 72)
    print("Sensitivity validation plots and table")
    print("-" * 72)

    loaded: Dict[str, Dict[str, np.ndarray]] = {}
    mode_summaries: Dict[str, List[Dict[str, Any]]] = {}

    for mode in ["tli", "mcc"]:
        csv_path = find_validation_csv(data_dir, mode)
        if csv_path is None:
            expected = data_dir / MODE_INFO[mode]["folder"] / MODE_INFO[mode]["csv"]
            print(f"[WARN] Missing {mode.upper()} validation CSV. Expected:\n       {expected}")
            continue

        data = read_validation_csv(csv_path, mode)
        loaded[mode] = data
        plot_ppo_success_scatter(data, output_dir)
        mode_summaries[mode] = summarize_by_cell(data)

        print(
            f"[OK] {mode.upper()}: N={len(data['ppo_success'])}, "
            f"PPO SR={100*np.mean(data['ppo_success']):.1f}%, "
            f"Nominal SR={100*np.mean(data['nominal_success']):.1f}%"
        )

    if not loaded:
        print("[WARN] No sensitivity validation CSV files found. No sensitivity plots/tables were generated.")
        return []

    for mode in ["tli", "mcc"]:

        if mode not in mode_summaries:
            continue

        tex_path = save_single_mode_table(
            mode_summaries[mode],
            mode,
            output_dir,
        )

        print(f"[OK] Saved {tex_path.name}")

    return mode_summaries


if __name__ == "__main__":
    main()
